In [ ]:
import torch

numpy version: 1.23.0


# 简单的数据

In [ ]:
X = torch.arange(12, dtype = torch.float32).reshape((3,4))
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X,Y),dim=0))
print(X==Y)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# 广播
a = torch.tensor([3,6,10]).reshape((3,1))
b = torch.tensor([1,3]).reshape((1,2))
print(a + b) # Broadcasting

tensor([[ 4,  6],
        [ 7,  9],
        [11, 13]])


In [ ]:
import os

os.makedirs(os.path.join('..\TRY_AI_SELF', 'data'), exist_ok=True)
data_file = os.path.join('..\TRY_AI_SELF', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

Traceback (most recent call last):
  File "c:\Users\Cu2O\.vscode\extensions\ms-python.python-2025.4.0-win32-x64\python_files\python_server.py", line 133, in exec_user_input
    retval = callable_(user_input, user_globals)
  File "<string>", line 5, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '..\\TRY_AI_SELFs\\data\\house_tiny.csv'



In [ ]:
# 读取数据
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [ ]:
# 填充缺失值

inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))  
print(inputs)

inputs = pd.get_dummies(inputs, dummy_na=True, dtype = type(0))  # 独热编码
print(inputs)



   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN
   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [ ]:
X, y = torch.tensor(inputs.values, dtype = torch.float32), torch.tensor(outputs.values)
print(X, y)

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]]) tensor([127500, 106000, 178100, 140000])
