# 自动求导

In [1]:
import torch

In [2]:
x = torch.arange(4.0)
x.requires_grad_(True)
y = 2 * torch.dot(x, x)
y.backward()
print(x.grad)  # dy/dx = 4 * x
print(x.grad == 4 * x)  # True

tensor([ 0.,  4.,  8., 12.])
tensor([True, True, True, True])


In [ ]:
x.grad.zero_()  # Reset gradients ，torch会累计梯度
y = x.sum()
y.backward()
print(x.grad)  # dy/dx = 1 for all elements

tensor([1., 1., 1., 1.])


## y.sum().backward()
loss一般是一个标量，而不是向量或者矩阵。所以“深度学习中，我们的目的不是计算微分矩阵，而是批量中每个样本单独计算的偏导数之和”，至于为什么需要批量计算每个样本的偏导数之和，我的理解是有时样本太多，一次计算需要占用很多内存，所以需将大样本分割为多个小样本进行累积计算。

y.sum()求得一个标量，相当于在反向积累的过程中在向量y后面增加了一步y.sum()。完整的过程是，先求y.sum()对y的导数，再求y对x的导数

In [ ]:
x.grad.zero_()  # Reset gradients
y = x * x
u = y.detach() # 常数
z = u * x

z.sum().backward()
print(x.grad == u)  # True

tensor([True, True, True, True])
