# 线性代数

In [ ]:
import torch
A = torch.arange(20,dtype = torch.float32).reshape(5,4)
print(A)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


In [ ]:
# 单纯使用等于
B = A
print(id(B), id(A))
B[2,:] = 0
print(A)

# 使用clone
B = A.clone()
print(id(B), id(A))
B[2,:] = 0
print(A)

2648215109520 2648215109520
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 0.,  0.,  0.,  0.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
2649609308896 2648215109520
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 0.,  0.,  0.,  0.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


In [ ]:
C = torch.arange(40).reshape((2,5,4))
print(C)
print(C.sum())
print(C.sum(axis=0), C.sum(axis=0).shape)
print(C.sum(axis=1), C.sum(axis=1).shape)
print(C.sum(axis=(0,1)), C.sum(axis=(0,1)).shape)

print(C.sum(axis=1,keepdims = True), C.sum(axis=1,keepdims = True).shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])
tensor(780)
tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]]) torch.Size([5, 4])
tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]]) torch.Size([2, 4])
tensor([180, 190, 200, 210]) torch.Size([4])
tensor([[[ 40,  45,  50,  55]],

        [[140, 145, 150, 155]]]) torch.Size([2, 1, 4])
